### ISSUE TITLE
MQmetrics error

### ISSUE THREAD

**Issue by sjefboeren** [svalvaro/MQmetrics#1]
MQmetrics running in RStudio under Windows10:

library(MQmetrics)
MQPathCombined <- 'F:\\2021\\21_09_20_Hongfei_Mark_Chen\\Chen\\combined'
MQCombined <- make_MQCombined(MQPathCombined, remove_contaminants = TRUE) 
generateReport(MQPathCombined)

Yields an almost empty Output file = D:\Documents\MQmetrics_report.pdf with only:

## Error in MaxQuantAnalysisInfo(MQcombined): object 'MQcombined' not found.

Directory using single \ instead of \\ or  ...\\combined "  or   ...\\combined\\' only slightly change the error message.
Has this software been tested under windows?

**Comment by svalvaro** [comment]
Hello @sjefboeren,

Thanks for providing feedback.

1. This is was indeed a bug that was due to a missing table. I have just updated the code so even in the case of missing tables, the plots and report will be generated. I have tested it on our Windows machine and works well even with missing tables.
2. For Windows forward slashes are necessary. 
     And add one at the end of the _combined_ : `'F:/2021/21_09_20_Hongfei_Mark_Chen/Chen/combined/'`
3. You don't need to use the function `make_MQCombined()` since the function `generateReport()` will do it.
4. The parameter `remove_contaminants = TRUE` is not needed since it is already TRUE by default. 

Please reinstall the package with:
```
library(devtools)
devtools::install_github("svalvaro/MQmetrics")
```

and then run MQmetrics:

```
library(MQmetrics)

MQPathCombined <- 'F:/2021/21_09_20_Hongfei_Mark_Chen/Chen/combined/'

generateReport(MQPathCombined)
```


Please let me know if this solved the issue.

**Comment by sjefboeren** [comment]
Thanks Alvaro. It is working now. That was a very fast response.
Best regards,
Sjef

**Comment by svalvaro** [comment]
You are welcome!
If you any comments feel free to contact me 👍🏻 
Best,
Alvaro
